@startuml "Paketabhängigkeiten"
' General
left to right direction
'top to bottom direction
skinparam linetype polyline
'skinparam linetype ortho
'skinparam nodesep 100
skinparam ranksep 100
skinparam shadowing false
skinparam legendBackgroundColor #White

legend bottom center
    = Legende
    | <#LightGreen>      | Medizininformatik-Initiative |
    | <#LightBlue>       | gematik GmbH |
    | <#LightPink>       | KBV / MIO42 GmbH |
    | <#Orange>          | DVMD e.V. |
    | <#MediumPurple>    | IHE International / Deutschland |
    | <size:20><U+21E2></size> | Abhängigkeitsbeziehung |
end legend

' MII
package "de.medizininformatikinitiative.kerndatensatz.dokument" as PkgMiiDokument #LightGreen {
    class "MII_PR_Dokument_Dokument" as MiiDokument
}
package "de.medizininformatikinitiative.kerndatensatz.fall" as PkgMiiFall #LightGreen {
    class "MII_PR_Fall_KontaktGesundheitseinrichtung" as MiiFall
}
package "de.medizininformatikinitiative.kerndatensatz.person" as PkgMiiPerson #LightGreen {
    class "MII_PR_Person_Patient" as MiiPatient
    class "MII_PR_Person_PatientPseudonymisiert" as MiiPseudonym
}

' Gematik
package "de.gematik.isik-dokumentenaustausch" as PkgIsik #LightBlue {
    class "ISiKDokumentenMetadaten" as GematikIsik
}

' KBV MIO
package "kbv.basis" as PkgMio #LightPink {
    class "KBV_PR_Base_DocumentReference" as KbvMio
}

' IHE International
package "ihe.iti.mhd" as PkgMhd #MediumPurple {
    class "UnContainedComprehensiveDocumentReference" as IheMhd
}
package "ihe.formatcode.fhir" as PkgIheFormatCode #MediumPurple {
    enum "IHE_FormatCode_vs" as IheFormatCode
}
package "de.ihe-d.terminology" as PkgIheTx #MediumPurple {
    enum "IHEXDSformatCodeDE" as IheDeFormatCode
    enum "IHEXDSclassCode" as IheDeClassCode
    enum "IHEXDStypeCode" as IheDeTypeCode
}

' DVMD e.V.
package "dvmd.kdl.r4" as PkgKdl #Orange {
    enum "ValueSetKDL" as DvmdKdl
}

' Explizite Abhängigkeiten
MiiDokument -[dashed,thickness=2]u-> MiiFall : "context.encounter"
MiiDokument -[dashed,thickness=2]u-> MiiPatient : "subject"
MiiDokument -[dashed,thickness=2]u-> MiiPseudonym : "subject"
MiiDokument -[dashed,thickness=2]u-> DvmdKdl : "type"
MiiDokument -[dashed,thickness=2]u-> IheFormatCode : "content.format"
MiiDokument -[dashed,thickness=2]u-> IheDeFormatCode : "content.format"
MiiDokument -[dashed,thickness=2]u-> IheDeClassCode : "category"
MiiDokument -[dashed,thickness=2]u-> IheDeTypeCode : "type"

' Berücksichtigte Abhängigkeiten (Profile)
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> GematikIsik : <color:DarkGrey>berücksichtigt</color>
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> KbvMio : <color:DarkGrey>berücksichtigt</color>
MiiDokument -[dashed,thickness=2,#DarkGrey]d-> IheMhd : <color:DarkGrey>berücksichtigt</color>

' Transitive Abhängigkeiten
'GematikIsik -[dashed]-> IheFormatCode
'GematikIsik -[dashed]-> IheMhd
'GematikIsik -[dashed]-> IheTerminology
'GematikIsik -[dashed]-> DvmdKdl
@enduml