@startuml Interne Dokumentennutzung

left to right direction

actor "Standort" as DIC
actor "Wissenschaftler:in" as RA

' Use Cases Datenintegrationszentrum
(Hausinterne\nAnfragen bearbeiten) as (Anfragen)
(Dokumentenarchiv\nnavigieren) as (Navigation)
(Dokument\narchivieren) as (Archivierung)
(Dokument\nkonvertieren) as (Konvertierung)
 
' Use Cases Wissenschaftler:in
(Dokument\nverarbeiten) as (Verarbeitung)
(Dokument\nannotieren) as (Annotation)
(Dokument\npseudonymisieren) as (Pseudonymisierung)

' Beziehungen
RA --> (Verarbeitung)
(Verarbeitung) .> (Pseudonymisierung) : <<include>>
(Verarbeitung) .> (Annotation) : <<include>>

DIC --> (Archivierung)
DIC --> (Konvertierung)
DIC --> (Anfragen)
(Anfragen) .> (Navigation) : <<include>>
  
note "Z.B. Gematik ISiK nach MII KDS" as NoteConversion
  (Konvertierung) .. NoteConversion
  
note "NLP Verarbeitungsschritte,\nz.B. Verarbeitgungsstatus" as NoteAnnotation
  (Verarbeitung) .. NoteAnnotation
  
@enduml