name: FHIR Profile Comparison

on:
  workflow_dispatch:
    inputs:
      isik_version:
        description: "Gematik ISiK FHIR IG version used to compare"
        required: true
        default: "5.1.0"
      mio_version:
        description: "KBV MIO FHIR IG version used to compare"
        required: true
        default: "1.7.0"
      mhd_version:
        description: "IHE MHD FHIR IG version used to compare"
        required: true
        default: "4.2.3"
  push:
    branches: 
      - main
      - master
      - balloting/**

  pull_request:
    branches: 
      - main
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download latest FHIR Validator CLI jar
        run: |
          wget -O validator_cli.jar https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar

      - name: Make compare.sh executable
        run: chmod +x ${{ github.workspace }}/docs/compare.sh

      - name: Run FHIR Validator
        env:
          WORKSPACE: ${{ github.workspace }}
          ISIK_VERSION: ${{ github.event.inputs.isik_version }}
          MIO_VERSION: ${{ github.event.inputs.mio_version }}
          MHD_VERSION: ${{ github.event.inputs.mhd_version }}
        run: |
          ${{ github.workspace }}/docs/compare.sh "${WORKSPACE}" "${ISIK_VERSION}" "${MIO_VERSION}" "${MHD_VERSION}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: github.event_name != 'pull_request'
        run: |
          git add docs
          if ! git diff --cached --quiet; then
            git commit -m "[FHIR Validator]: Updates FHIR Validator comparison results"
            git push
          fi